# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all$aws$localip$cmd_duration$line_break$character"""

[character]
success_symbol = '[](cyan)'
error_symbol = '[](red)'

[memory_usage]
disabled = false
style = "dimmed white"

[localip]
ssh_only = false
format = "[$localipv4]($style) "
disabled = false

[directory]
style = "cyan"

[git_status]
style = "purple"

[git_branch]
style = "purple"

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[aws]
force_display = true
symbol = "☁️ "

[kubernetes]
disabled=false
format = '[$symbol$user/$context( \($namespace\))]($style) in '	
detect_env_vars = ["OC_LOGGED_IN"]

[[kubernetes.contexts]]
context_pattern = ".*/api-(?P<cluster>\\w+).*"
context_alias = "$cluster"
user_pattern = "(?P<username>.*)/.*"
user_alias = "$username"

# DISABLED

[gcloud]
disabled = true

[kotlin]
disabled = true

[swift]
disabled = true
