format = """$all$line_break$character"""

[character]
success_symbol = "[>](bold cyan)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold cyan)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_replace_one_symbol = "[<](bold purple)"

[git_status]
style = "bold purple"

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[aws]
format = '(on [$symbol$profile ]($style))'
symbol = '☁️ '

[kubernetes]
disabled=false
format = '[$symbol$user/$context( \($namespace\))]($style) in '	
detect_env_vars = ["OC_LOGGED_IN"]

[[kubernetes.contexts]]
context_pattern = ".*/api-(?P<cluster>\\w+).*"
context_alias = "$cluster"
user_pattern = "(?P<username>.*)/.*"
user_alias = "$username"

# DISABLED

[gcloud]
disabled = true

[kotlin]
disabled = true

[swift]
disabled = true
